DROP TABLE IF EXISTS public.user_login;
CREATE TABLE user_login (
id BIGSERIAL NOT NULL PRIMARY KEY,
login VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
create_time timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL);
